apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app-from-s3
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: Bucket
    name: flux-s3-source
  path: "./"
  prune: true
